spring:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:file:D:/dev/demo.db
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
jwt:
  token:
    secret: 12345
    life-time: 30
