--liquibase formatted sql
--changeset alex:simple_user
create table simple_user (
    id integer generated by default as identity,
    password varchar(255) not null,
    username varchar(255) not null,
    algorithm varchar(255) not null,
    primary key (id)
);

--changeset alex:authorities
create table authority (
    id integer generated by default as identity,
    authority varchar(255) not null,
    simple_user integer not null,
    primary key (id)
);

--changeset alex:create_user
insert into simple_user (id, username, password, algorithm)
values (1, 'alex', '$2a$04$DwweMgIeOKmZGIAGG6QEuOopTgiWwlEam9.0386Ta42Ig6HdJIM4S', 'BCRYPT');

--changeset alex:create_authorities
insert into authority (id, authority, simple_user) values (1, 'READ', 1);
insert into authority (id, authority, simple_user) values (2, 'WRITE', 1);
