--liquibase formatted sql
--changeset alex:init
create table simple_user (
    id integer generated by default as identity,
    authority varchar(255),
    password varchar(255),
    username varchar(255),
    primary key (id)
);
alter table simple_user add constraint SIMPLE_USER_USERNAME unique (username);

--changeset alex:create_user
insert into simple_user (id, username, password, authority)
values (default, 'alex', '123', 'read');
--rollback delete simple_user where username = 'alex';
